In [156]:
import pandas as pd

In [157]:
data = pd.read_csv('dataset.csv', low_memory = False)

In [158]:
#drop null conditions/numerical conditions
data.dropna(subset=['trackable_name'])
data = data[~data['trackable_name'].str.contains('\d', na = False)]
data

,user_id,age,sex,country,checkin_date,trackable_id,trackable_type,trackable_name,trackable_value
0,QEVuQwEABlEzkh7fsBBjEe26RyIVcg==,NaN,NaN,NaN,2015-11-26,1069,Condition,Ulcerative colitis,0
1,QEVuQwEAWRNGnuTRqXG2996KSkTIEw==,32.0,male,US,2015-11-26,1069,Condition,Ulcerative colitis,0
2,QEVuQwEA+WkNxtp/qkHvN2YmTBBDqg==,2.0,female,CA,2017-04-28,3168,Condition,pain in left upper arm felt like i was getting...,4
3,QEVuQwEA+WkNxtp/qkHvN2YmTBBDqg==,2.0,female,CA,2017-04-28,3169,Condition,hip pain when gettin up,3
4,QEVuQwEA+WkNxtp/qkHvN2YmTBBDqg==,2.0,female,CA,2017-04-28,3170,Condition,pain in hand joints,4
...,...,...,...,...,...,...,...,...,...
7976218,QEVuQwEAtlfm8VyoxZ9biWjDHb74gQ==,22.0,female,GB,2019-12-04,1,Tag,tired,NaN
7976219,QEVuQwEAtlfm8VyoxZ9biWjDHb74gQ==,22.0,female,GB,2019-12-04,2,Tag,stressed,NaN
7976220,QEVuQwEAtlfm8VyoxZ9biWjDHb74gQ==,22.0,female,GB,2019-12-04,9002,Food,soup,NaN
7976221,QEVuQwEAtlfm8VyoxZ9biWjDHb74gQ==,22.0,female,GB,2019-12-04,9139,Food,yogurt,NaN
7976222,QEVuQwEAtlfm8VyoxZ9biWjDHb74gQ==,22.0,female,GB,2019-12-04,10260,Food,granola,NaN

In [159]:
#clean raynaud's
data['trackable_name'].replace(".*(?i)rayna.*", "Raynaud's Phenomenon", regex=True, inplace=True)

In [160]:
#clean ibs
data['trackable_name'].replace(".*IBS.*", "IBS", regex=True, inplace=True)
data['trackable_name'].replace(".*(?i)bowel (?i)syndrome.*", "IBS", regex=True, inplace=True)

In [161]:
#clean ibd
data['trackable_name'].replace(".*IBD.*", "IBD", regex=True, inplace=True)
data['trackable_name'].replace(".*(?i)bowel (?i)di.*", "IBD", regex=True, inplace=True)

In [162]:
#clean chron's
data['trackable_name'].replace(".*(?i)chron['|â€™]*s.*", "Chron's", regex=True, inplace=True)

In [163]:
#clean scleroderma
data['trackable_name'].replace(".*(?i)scleroderma.*", "Scleroderma", regex=True, inplace=True)

In [164]:
#clean lupus
data['trackable_name'].replace(".*(?i)lupus.*", "Lupus", regex=True, inplace=True)

In [165]:
#Rheumatoid arthritis
data['trackable_name'].replace(".*(?i)rheumatoid (?i)arthritis.*", "Rheumatoid Arthritis", regex=True, inplace=True)

In [166]:
#clean Fibromyalgia, excluded fibromya
data['trackable_name'].replace(".*(?i)fibromyalgia.*", "Fibromyalgia", regex=True, inplace=True)
data['trackable_name'].replace(".*(?i)fibromalgia.*", "Fibromyalgia", regex=True, inplace=True)
data['trackable_name'].replace(".*(?i)fibromyalgi.*", "Fibromyalgia", regex=True, inplace=True)
data['trackable_name'].replace(".*(?i)fibromyaglia.*", "Fibromyalgia", regex=True, inplace=True)
data['trackable_name'].replace(".*(?i)fibromyalgeia.*", "Fibromyalgia", regex=True, inplace=True)
data['trackable_name'].replace(".*(?i)fibromylaga.*", "Fibromyalgia", regex=True, inplace=True)
data['trackable_name'].replace(".*(?i)fibromyaliga.*", "Fibromyalgia", regex=True, inplace=True)
data['trackable_name'].replace(".*(?i)fibromygia.*", "Fibromyalgia", regex=True, inplace=True)
data['trackable_name'].replace(".*(?i)fibromylagia.*", "Fibromyalgia", regex=True, inplace=True)
data['trackable_name'].replace(".*(?i)fibromialgia.*", "Fibromyalgia", regex=True, inplace=True)
data['trackable_name'].replace(".*(?i)fibromylgia.*", "Fibromyalgia", regex=True, inplace=True)

In [167]:
#clean Dysautonomia
data['trackable_name'].replace(".*(?i)dysautonomia.*", "Dysautonomia", regex=True, inplace=True)

In [168]:
#Psoriatic arthritis ok
data['trackable_name'].replace(".*(?i)psoriatic (?i)arthritis.*", "Psoriatic Arthritis", regex=True, inplace=True)

In [169]:
#clean Psoriasis
data['trackable_name'].replace(".*(?i)psoriasis.*", "Psoriasis", regex=True, inplace=True)

In [170]:
#arthritis
data['trackable_name'].replace("(?i)arthritis", "Arthritis", regex=True, inplace=True)

In [171]:
#keep only the id's that have logged our diseases
ourcond = {'trackable_name':
                 ["Scleroderma","IBS","IBD","Chron's", "Lupus", "Rheumatoid Arthritis", "Fibromyalgia",
                 "Dysautonomia", "Psoriatic arthritis", "Arthritis", "Psoriasis", "Raynaud's Phenomenon"]}
ourconditions = pd.DataFrame(data = ourcond)
ourconditions.head(11)

          trackable_name
0            Scleroderma
1                    IBS
2                    IBD
3                Chron's
4                  Lupus
5   Rheumatoid Arthritis
6           Fibromyalgia
7           Dysautonomia
8    Psoriatic arthritis
9              Arthritis
10             Psoriasis

In [172]:
#create table with id's of users who logged autoummune conditions
idswithcond = pd.merge(data, ourconditions, on="trackable_name")
idswithcond = idswithcond.drop_duplicates(subset = ['user_id'])
idswithcond = idswithcond['user_id']

In [173]:
#export to CSV
idswithcond
#idswithcond.to_csv('idswithcond.csv')

0         QEVuQwEAzZl+kJVQFj2hY5xrzOcbnA==
1         QEVuQwEA6PPwjZ8tnqC1KHhapbdMpQ==
2         QEVuQwEAT556zzFRIWMYQwW/SuVuQg==
4         QEVuQwEADFtnDHECcyAylMlv1pPa/Q==
9         QEVuQwEAzpzYWRcIal+buxDuBeRqrw==
                        ...
142107    QEVuQwEALscEpUPriwHRBKu2zjOXvw==
142108    QEVuQwEACkTTju/3vtPjiNltwQqw4w==
142109    QEVuQwEACyoL8i5Rms/0QMRoKsfxww==
142139    QEVuQwEALilfGtIuTjy5Bo5tIlnnxQ==
142140    QEVuQwEAB1IRayLNuCsvNj+6kV1pTg==
Name: user_id, Length: 14311, dtype: object

In [174]:
#clean original data to only contain the entries from users that report autoimmune conditions
usefuldata = pd.merge(data, idswithcond, on="user_id")
#remove users that have <= 10 entries
usefuldata = usefuldata.groupby('user_id').filter(lambda x: len(x) > 10)

In [175]:
usefuldata

,user_id,age,sex,country,checkin_date,trackable_id,trackable_type,trackable_name,trackable_value
0,QEVuQwEAzZl+kJVQFj2hY5xrzOcbnA==,NaN,NaN,NaN,2015-05-25,350,Condition,Ehlers-Danlos syndrome,0
1,QEVuQwEAzZl+kJVQFj2hY5xrzOcbnA==,NaN,NaN,NaN,2015-05-25,397,Condition,Fibromyalgia,0
2,QEVuQwEAzZl+kJVQFj2hY5xrzOcbnA==,NaN,NaN,NaN,2015-05-25,561,Condition,IBS,0
3,QEVuQwEAzZl+kJVQFj2hY5xrzOcbnA==,NaN,NaN,NaN,2015-05-25,1131,Condition,Chronic Migraines,1
4,QEVuQwEAzZl+kJVQFj2hY5xrzOcbnA==,NaN,NaN,NaN,2015-05-25,1,Symptom,Abdominal pain,0
...,...,...,...,...,...,...,...,...,...
3664054,QEVuQwEA/3ZnJPHdtLiOWBy1VAYIYA==,48.0,male,GB,2019-12-04,9010,Tag,Frequent urination,NaN
3664055,QEVuQwEA/3ZnJPHdtLiOWBy1VAYIYA==,48.0,male,GB,2019-12-04,8935,Food,water,NaN
3664056,QEVuQwEA/3ZnJPHdtLiOWBy1VAYIYA==,48.0,male,GB,2019-12-04,8960,Food,chicken sandwich,NaN
3664057,QEVuQwEA/3ZnJPHdtLiOWBy1VAYIYA==,48.0,male,GB,2019-12-04,9119,Food,toast,NaN
3664058,QEVuQwEA/3ZnJPHdtLiOWBy1VAYIYA==,48.0,male,GB,2019-12-03,9951,Treatment,Mesalazine,1g

In [176]:
#order data by id and date to facilitate date normalization
usefuldata.sort_values(by=['user_id','checkin_date'], inplace=True)

In [177]:
#export to CSV
usefuldata
#usefuldata.to_csv('autoimmune_data.csv')

,user_id,age,sex,country,checkin_date,trackable_id,trackable_type,trackable_name,trackable_value
2869570,QEVuQwEA++z6GMJgxyjYYw0jFdXeDw==,30.0,female,BE,2019-09-19,1288,Condition,Leaky Gut,1
2869571,QEVuQwEA++z6GMJgxyjYYw0jFdXeDw==,30.0,female,BE,2019-09-19,649,Condition,Migraine,0
2869572,QEVuQwEA++z6GMJgxyjYYw0jFdXeDw==,30.0,female,BE,2019-09-19,1022,Condition,Thoracic outlet syndrome,2
2869573,QEVuQwEA++z6GMJgxyjYYw0jFdXeDw==,30.0,female,BE,2019-09-19,886,Condition,Rheumatoid Arthritis,2
2869574,QEVuQwEA++z6GMJgxyjYYw0jFdXeDw==,30.0,female,BE,2019-09-19,397,Condition,Fibromyalgia,3
...,...,...,...,...,...,...,...,...,...
1884818,QEVuQwEAzzbGedVTDIuQFBYxXLlPxQ==,48.0,male,US,2019-04-21,175150,Weather,temperature_min,42.0
1884819,QEVuQwEAzzbGedVTDIuQFBYxXLlPxQ==,48.0,male,US,2019-04-21,175150,Weather,temperature_max,78.0
1884820,QEVuQwEAzzbGedVTDIuQFBYxXLlPxQ==,48.0,male,US,2019-04-21,175150,Weather,precip_intensity,0.0001
1884821,QEVuQwEAzzbGedVTDIuQFBYxXLlPxQ==,48.0,male,US,2019-04-21,175150,Weather,pressure,1015.0
1884822,QEVuQwEAzzbGedVTDIuQFBYxXLlPxQ==,48.0,male,US,2019-04-21,175150,Weather,humidity,41.0

In [178]:
#reset index in the new dataset
usefuldata_dated = usefuldata.copy()
usefuldata_dated.reset_index(drop=True, inplace=True)

In [180]:
#Update dates and make user ID's more readable
cur_date = usefuldata_dated.at[0,'checkin_date'] #current date
cur_id = usefuldata_dated.at[0,'user_id'] #current user id
day_num = 1
new_id = 1 #relable with more readable user id's
for i, row in usefuldata_dated.iterrows():
    if cur_id == usefuldata_dated.at[i,'user_id']:#check if we are on the same user
        #check if the date of the entry is same as the last one, if so number it the same num
        usefuldata_dated.at[i,'user_id'] = new_id
        if cur_date == usefuldata_dated.at[i,'checkin_date']:
            usefuldata_dated.at[i,'checkin_date'] = day_num #change date to day num
        else: #go to next date
            day_num += 1
            cur_date = usefuldata_dated.at[i,'checkin_date'] #update current date
            usefuldata_dated.at[i,'checkin_date'] = day_num
    else: #go on to the next user
        new_id += 1
        cur_id = usefuldata_dated.at[i,'user_id'] #update current user id
        usefuldata_dated.at[i,'user_id'] = new_id
        cur_date = usefuldata_dated.at[i,'checkin_date'] #update current date
        day_num = 1
        usefuldata_dated.at[i,'checkin_date'] = day_num #relable date

In [181]:
usefuldata_dated

,user_id,age,sex,country,checkin_date,trackable_id,trackable_type,trackable_name,trackable_value
0,1,30.0,female,BE,1,1288,Condition,Leaky Gut,1
1,1,30.0,female,BE,1,649,Condition,Migraine,0
2,1,30.0,female,BE,1,1022,Condition,Thoracic outlet syndrome,2
3,1,30.0,female,BE,1,886,Condition,Rheumatoid Arthritis,2
4,1,30.0,female,BE,1,397,Condition,Fibromyalgia,3
...,...,...,...,...,...,...,...,...,...
3649702,11733,48.0,male,US,12,175150,Weather,temperature_min,42.0
3649703,11733,48.0,male,US,12,175150,Weather,temperature_max,78.0
3649704,11733,48.0,male,US,12,175150,Weather,precip_intensity,0.0001
3649705,11733,48.0,male,US,12,175150,Weather,pressure,1015.0
3649706,11733,48.0,male,US,12,175150,Weather,humidity,41.0

In [182]:
#export to CSV
usefuldata_dated.to_csv('autoimmune_data_dated.csv')

In [184]:
#count number of unique users who logged each condition
tocount = pd.merge(usefuldata_dated, ourconditions, on="trackable_name")
(tocount.groupby('trackable_name')['user_id'].nunique())

trackable_name
Arthritis                793
Chron's                   27
Dysautonomia             660
Fibromyalgia            6809
IBD                      163
IBS                     3461
Lupus                   1379
Psoriasis                480
Raynaud's Phenomenon     734
Rheumatoid Arthritis    1008
Scleroderma               59
Name: user_id, dtype: int64